controller_list:
  - name: fake_a_bot_controller
    joints:
      - a_bot_shoulder_pan_joint
      - a_bot_shoulder_lift_joint
      - a_bot_elbow_joint
      - a_bot_wrist_1_joint
      - a_bot_wrist_2_joint
      - a_bot_wrist_3_joint
  - name: fake_b_bot_controller
    joints:
      - b_bot_shoulder_pan_joint
      - b_bot_shoulder_lift_joint
      - b_bot_elbow_joint
      - b_bot_wrist_1_joint
      - b_bot_wrist_2_joint
      - b_bot_wrist_3_joint
  - name: fake_c_bot_controller
    joints:
      - c_bot_shoulder_pan_joint
      - c_bot_shoulder_lift_joint
      - c_bot_elbow_joint
      - c_bot_wrist_1_joint
      - c_bot_wrist_2_joint
      - c_bot_wrist_3_joint
  - name: fake_front_bots_controller
    joints:
      - a_bot_shoulder_pan_joint
      - a_bot_shoulder_lift_joint
      - a_bot_elbow_joint
      - a_bot_wrist_1_joint
      - a_bot_wrist_2_joint
      - a_bot_wrist_3_joint
      - b_bot_shoulder_pan_joint
      - b_bot_shoulder_lift_joint
      - b_bot_elbow_joint
      - b_bot_wrist_1_joint
      - b_bot_wrist_2_joint
      - b_bot_wrist_3_joint
  - name: fake_all_bots_controller
    joints:
      - a_bot_shoulder_pan_joint
      - a_bot_shoulder_lift_joint
      - a_bot_elbow_joint
      - a_bot_wrist_1_joint
      - a_bot_wrist_2_joint
      - a_bot_wrist_3_joint
      - b_bot_shoulder_pan_joint
      - b_bot_shoulder_lift_joint
      - b_bot_elbow_joint
      - b_bot_wrist_1_joint
      - b_bot_wrist_2_joint
      - b_bot_wrist_3_joint
      - c_bot_shoulder_pan_joint
      - c_bot_shoulder_lift_joint
      - c_bot_elbow_joint
      - c_bot_wrist_1_joint
      - c_bot_wrist_2_joint
      - c_bot_wrist_3_joint
initial:
  - group: a_bot
    pose: home_a
  - group: b_bot
    pose: home_b
  - group: c_bot
    pose: home_c
  - group: front_bots
    pose: home_front
  - group: all_bots
    pose: home_all
